targets:
  dev:
    mode: development
    default: true
    resources:
      jobs:
        document_ingestion_job:
          job_clusters:
            - job_cluster_key: ingestion_cluster
              new_cluster:
                num_workers: 1
                node_type_id: Standard_DS3_v2
          schedule:
            pause_status: PAUSED
