targets:
  staging:
    mode: development
    resources:
      jobs:
        document_ingestion_job:
          job_clusters:
            - job_cluster_key: ingestion_cluster
              new_cluster:
                num_workers: 2
          schedule:
            pause_status: PAUSED
